/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e341abd0e3805651222dd39
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
import { Observable } from 'rxjs';

// Import Services
import { SkuService } from '../../services/sku.service';
// Import Models
import { Sku } from '../../domain/ang-pwafirestore_db/sku';

// START - USED SERVICES

// END - USED SERVICES

/**
 * This component shows a list of Sku
 * @class SkuListComponent
 */
@Component({
    selector: 'app-sku-list',
    templateUrl: './sku-list.component.html',
    styleUrls: ['./sku-list.component.css']
})
export class SkuListComponent implements OnInit {
    list: Observable<any[]>;
    search: any = {};
    idSelected: string;
    constructor(
        private skuService: SkuService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.list = this.skuService.list();
    }

    /**
     * Select Sku to remove
     *
     * @param {string} id Id of the Sku to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Sku
     */
    deleteItem() {
        this.skuService.remove(this.idSelected);
    }

}
