/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE skuBaseService PLEASE EDIT ../sku.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Sku } from '../../domain/ang-pwafirestore_db/sku';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Sku.service.ts
 */

/*
 * SCHEMA DB Sku
 *
	{
		description: {
			type: 'String'
		},
		title: {
			type: 'String',
			required : true
		},
		type: {
			type: 'String',
			required : true,
			enum : ["Labour", "Material", "Other"]
		},
		unit: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class SkuBaseService {

    private skuCollection: AngularFirestoreCollection<Sku>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.skuCollection = afs.collection<Sku>('sku');
    }


    // CRUD METHODS

    /**
    * SkuService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Sku): Promise<DocumentReference> {
        return this.skuCollection.add(item);
    }

    /**
    * SkuService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.skuCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * SkuService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Sku> {
        return this.afs.doc<Sku>('sku/' + id);
    }

    /**
    * SkuService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Sku[]> {
        return this.afs.collection('sku').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Sku;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * SkuService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Sku>, item: Sku): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
